apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi