apiVersion: batch/v1
kind: Job
metadata:
  name: train
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: mlops-train:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-server:5000"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"