FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow==3.15.1

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "/app/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"]