FROM python:3.13-slim

WORKDIR /app
ENV GIT_PYTHON_REFRESH=quiet

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY api/ api/
COPY data/processed/features.csv data/processed/features.csv

CMD ["python", "-m", "src.models.registry"]